/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Casa.gltf --transform 
Files: Casa.gltf [9.93KB] > C:\Users\Draken\Desktop\3D\Web\Casa\Casa-transformed.glb [702.61KB] (-6976%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useSpring, animated, config } from '@react-spring/three'

export function Casa(props) {
  const { scale } = useSpring({
    scale: true ? 1.5 : 1,
    config: config.wobbly,
  })
  const { nodes, materials } = useGLTF('/Casa-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plano.geometry} material={materials.Material} position={[0, 0, -10]} scale={[15, 1, 30]} />
      <group position={[-25.579, 19.618, 0]}>
        <mesh geometry={nodes.Cubo_1.geometry} material={materials.Metal} castShadow={true} receiveShadow={true} />
        <mesh geometry={nodes.Cubo_2.geometry} material={materials.Vidrio} castShadow={true} receiveShadow={true} />
        <animated.mesh scale={scale} onClick={() => setActive(!active)} ref={myMesh}>
          <boxGeometry />
          <meshPhongMaterial color="royalblue" />
        </animated.mesh>
      </group>
      <mesh geometry={nodes.Cubo003.geometry} material={nodes.Cubo003.material} position={[-46.488, 7.226, -18.485]} receiveShadow={true} castShadow={true} rotation={[0, 0, -Math.PI]} scale={[-0.19, -0.222, -23.169]} />
    </group>
  )
}

useGLTF.preload('/Casa-transformed.glb')
