/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Casa.gltf --transform 
Files: Casa.gltf [29.16KB] > C:\Users\Draken-101\Desktop\3D\Web\Casa\Casa-transformed.glb [1.45MB] (-4856%)
*/

import { useGLTF } from '@react-three/drei'
import { Luz } from './Luces';
import { useUserContext } from '../../Context/useContext';
import { useEffect, useState } from 'react';
import { FocoCocina } from '../Focos/FocoCocina';
import { FocoCuarto } from '../Focos/FocoCuarto';
import { FocoPorton1 } from '../Focos/FocoPorton1';
import { FocoPorton2 } from '../Focos/FocoPorton2';
import { FocoPasillo } from '../Focos/FocoPasillo';

export function Casa(props) {
  const { devices } = useUserContext();
  const { nodes, materials } = useGLTF('/Casa-transformed.glb');
  const [focos, setFocos] = useState([]);

  useEffect(() => {
    devices?.map(device => {
      if (device?.name?.includes('Foco')) {
        console.log(device);
        setFocos(prevFocos => [...prevFocos, device])
      }
    })
    return () => {

    };
  }, [devices]);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry} material={materials['Material.002']} position={[-1.037, 0.01, -24.557]} scale={71.251} />
      <group position={[10.965, 12.203, -1.607]} rotation={[Math.PI, 0, Math.PI]} scale={1.859}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry} material={materials.WoodQuarteredChiffon001_2K} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry} material={materials['Material.004']} />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.matress.geometry} material={materials.PaletteMaterial001} position={[10.965, 12.315, -1.607]} rotation={[Math.PI, 0, Math.PI]} scale={[2.851, 0.211, 1.789]} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.blanket.geometry} material={materials.FabricUpholsteryMidCenturyPebbles001_2K} position={[10.444, 13.464, -1.607]} rotation={[Math.PI, 0, Math.PI]} scale={[2.514, 1.859, 2.376]} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stand_top.geometry} material={materials.PaletteMaterial002} position={[0, -0.568, 1.201]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.044, 0.289, 0.193]} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.light_power.geometry} material={materials.PaletteMaterial003} position={[-9.463, 12.478, 2.223]} rotation={[Math.PI / 2, 0, -1.702]} scale={0.002} />
      <group position={[14.512, 9.226, -3.485]} rotation={[0, 0, -Math.PI]} scale={[-0.19, -0.222, -23.169]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Clima.geometry} material={materials.PaletteMaterial004} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Clima_1.geometry} material={materials['Material.003']} />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cubo.geometry} material={materials.PaletteMaterial005} position={[-12.521, 14.006, -13]} rotation={[0, -Math.PI / 2, 0]} scale={[1, 1.556, 1.275]} />
      {/* Cuarto 2, 20, 0 */}
      {/* Cocina 0, 20, -8 */}
      {/* Pasillo -8, 20, 7 */}
      <FocoCocina/>
      <FocoCuarto/>
      <FocoPasillo/>
      <FocoPorton1/>
      <FocoPorton2/>
    </group>
  )
}

useGLTF.preload('/Casa-transformed.glb')
